name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: MEND Action
        uses: ./
        with:
          wssURL: "https://saas-eu.whitesourcesoftware.com/agent"
          apiKey: "20acb371952347988eef7427128dca0667fab8f6de9946eaa97ec05048284cf4"
          userKey: "d2896e4db4694a25af2adb2919b2849509a98142b7704f9ca50247463736a991"
          productName: "PRd_naap"
          projectName: "Stefano_poc"

      - name: check for hello.ts.net in netmap
        run:
          ls -lrt
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Adjust this version to the Go version you need

      # Build the Go app
      - name: Build
        run: go build

      # Run tests
      - name: Test
        run: go test ./...

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Adjust this version to the Go version you need

      # Install and run security scanner (e.g., Gosec)
      - name: Install Gosec
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin v2.8.0
      - name: Run Gosec
        run: gosec -quiet ./...

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Adjust this version to the Go version you need

      # Build the Go app
      - name: Build
        run: go build

      # You can add further steps here to deploy your app

# Add more jobs and steps as per your specific requirements (e.g., deployment)
